name: Release and Deploy Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: Detectar versão e publicar na Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Mostrar versão
        run: echo "Publicando versão ${GITHUB_REF_NAME}"

      - name: Instalar dependências
        run: npm install

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull das configurações da Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Gerar build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy para Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}